### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by MacedonskyAlex** [willis81808/MultiplayerUnlimiter#2]
I put a slider for 20 players, but in the lobby it still shows a game for 8 players

**Comment by willis81808** [comment]
Previously it did not dynamically update the display on any open windows.

As of version `0.1.1` it will now update the display in the lobby, and in the player list while in-game. If the number you see in the window doesn't match what it should be, try adjusting the slider to some other number then back to your desired limit, and the text should update.
